### PR TITLE
DSA-110 FRB photometry from Sharma et al (2024)

### PR DESCRIPTION
**Pull request by caseyjlaw**
The missing values are negative, but not exactly the same as used by others.
Let me know what you think.

### CODE REVIEW

**Comment by caseyjlaw** [comment]
Anything I can do to advance this? My plan was to get this merged and then work on the hosts.

**Comment by profxj** [comment]
Thanks for this, @caseyjlaw !

Any chance you can make the bad values -999. instead of a range of negative values?

**Comment by profxj** [comment]
oh, and the filters will need to match the schema described in here:

https://github.com/FRBs/FRB/blob/main/frb/galaxies/defs.py

and the magnitudes are assumed to *not* have been corrected for Galactic extinction.
The code will do that for you.   Thanks!

**Comment by caseyjlaw** [comment]
I've modified the csv (and added a def) according to your suggestion. Do the CI tests cover validation of csv files or should I test another way?

**Comment by profxj** [comment]
Well, the next steps are to generate JSON files for the hosts which is probably
  easiest for me to do.  

But, it would be easier on me if this were a branch in the Repo (instead of grabbing your fork).

So, I suggest we redirect this PR into a branch 
  and then work on that branch together.  

Good by you, @caseyjlaw ?

**Comment by profxj** [comment]
I should add, the JSON files are auto-generated, e.g.

`frb_build Hosts --frb TNS`

but there is a fair bit of public data downloading that goes on 
  which requires additional packages, etc.

**Comment by caseyjlaw** [comment]
Merging via a branch is fine by me. This PR is going from a new branch on my fork to a new branch on the main repo. We could just approve and merge into that new branch, then merge again into main after doing the work you suggested.

**Comment by profxj** [comment]
Ah, I had missed that! :)

Am approving and merging now.  and we can issue a new PR from 
that branch eventually.

**Comment by caseyjlaw** [comment]
Ok, just let me know how I can help.

**Pull request merged**
