### PR TITLE
bug fix and added full run test

### PR DESCRIPTION
**Pull request by lluism**

### CODE REVIEW

**Comment by lluism** [comment]
bug fix and added full run test

**Comment by profxj** [comment]
@lluism -- can you double check why the change I made for R155 (see the CHIME Slack)
had no effect?  I don't see a bug but...

thx

**Comment by lluism** [comment]
@profxj  I merged the pz_dm and limiting_mag scripts into a pzdm_mag one, with its new call command frb_pzdm_mag. Now the code returns redshift and luminosity info, with same defaults and arguments that were there before. The tests have also been changed to test the new script and not the individual previous ones. Once we confirm all this works, I will delete the two individual pieces (i made a note on it). Thanks !

**Review by profxj — APPROVED** [review]
thanks for all of this.

tests are failing but in a non-obvious way

I am going to approve and merge for now
and kick the can down the road..

**Pull request merged**
