### PR TITLE
Check if a coordinate is within a survey footprint

### PR DESCRIPTION
**Pull request by SunilSimha**
As titled.

### CODE REVIEW

**Review by profxj — CHANGES_REQUESTED** [review]
Nice stuff.  Can you add a small test?
Thanks!

**Comment by SunilSimha** [comment]
@profxj, the tests are breaking as GitHub is unable to import `astroquery.SDSS` for some reason. I see that `astroquery` is listed as a conda dependency in the travis file so I'm not sure what's breaking it.

**Comment by profxj** [comment]
@SunilSimha  -- you need to modify this file:

https://github.com/FRBs/FRB/blob/main/.github/workflows/ci_tests.yml

**Comment by SunilSimha** [comment]
@profxj. Thanks! I've decided to ignore the `astropy` dev branches in the test for now because it's doing something weird with `astroquery.heasarc`. Namely, switching to the dev branch returns zero objects from `heasarc` in the test query whereas the stable `astropy` branch results in one to two objects.

Let me know if this is okay.

**Review by profxj — APPROVED** [review]
great stuff

**Pull request merged**
