### PR TITLE
Tns

### PR DESCRIPTION
**Pull request by astro-vic**
Merging TNS script to main.

### CODE REVIEW

**Review by profxj — APPROVED** [review]
looks great!

**Comment by caseyjlaw** [comment]
This is a nice tool!
I see the API key in the code. Best to keep that private and import at run time.

**Comment by profxj** [comment]
Good catch!

**Comment by astro-vic** [comment]
@caseyjlaw I made the API key specifically for TNS and it was intended for public use in case other people don't have one. Would you still recommend hiding it?

**Comment by caseyjlaw** [comment]
I see. The purpose of the key is to control access and make people responsible for users of the key. If you create one and share it widely, then people may abuse it.
Do you think it is reasonable to ask users to create their own, which can be passed in as an argument? Honestly, I'm not picky. This pull request is the first I've heard of your idea!

**Comment by astro-vic** [comment]
@caseyjlaw I think it is pretty easy for them to make one. Maybe I can ask users to create their own and pass in as an argument but make a note saying if they just want to try out the code, they can reach out to me and I will give they my key? I just want to make it accessible to the users! 

Yes, it's actually been sitting there for a while and I just now submitted a PR for it :(

**Comment by caseyjlaw** [comment]
I think that's a reasonable policy. I like to use a pattern like with environment variables set automatically in the .bashrc (which is secure and easy). In the code something like:
```
from os import environ
if "TNS_API_KEY" in environ:
    tnskey =  environ["TNS_API_KEY"]
else:
    ... (logging to ask to set or input key) ...
```

**Review by profxj — CHANGES_REQUESTED** [review]
The test now fails for me.

Please tell me what I need to do to get it to pass.
Thx

**Comment by astro-vic** [comment]
@caseyjlaw, I have incorporated your suggestion in the script, see if that all looks good?

**Comment by astro-vic** [comment]
> 

Just updated the script, the only thing needed would be an API key, name and ID of your bot! I can give those to you if you don't have one! Try and see if that works!

**Review by caseyjlaw — APPROVED** [review]

**Review by profxj — APPROVED** [review]
tests passing, giddy up!

**Pull request merged**
