### PR TITLE
Wise refactor

### PR DESCRIPTION
**Pull request by SunilSimha**
As titled. Includes a revamped `WISE_Survey` class that can slurp ["standard" aperture mags](https://wise2.ipac.caltech.edu/docs/release/allwise/expsup/sec2_1a.html#w1mag) instead of the PSF mags. The class can also get image cutouts now.

### CODE REVIEW

**Review by profxj — CHANGES_REQUESTED** [review]
This looks great.  Please add a test or two
to confirm it is working as intended.

Thanks!

**Review by muethela — COMMENTED** [review]
Everything looks good to me!

**Comment by SunilSimha** [comment]
I'm removing the automatic slurping of WISE data from `DES_Survey` as that functionality is no longer enabled by `datalab`. Also, no reason why `DES` should get special treatment. :) 

To return the functionality in a more robust manner, we should probably create a function that looks for data in all surveys and cross-matches sources to produce a giant table of photometry. Perhaps a task for a different PR.

**Comment by SunilSimha** [comment]
Just resolved all merge conflicts due to removing the WISE cross match from DES. Ignore all the duplicate commits.

**Comment by SunilSimha** [comment]
Adding test results here.

```python
============================= test session starts ==============================
platform linux -- Python 3.7.11, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/sunil/Python/FRB
plugins: astropy-header-0.1.2, remotedata-0.3.2, hypothesis-6.14.1, doctestplus-0.10.1, openfiles-0.5.0, arraydiff-0.3
collected 8 items

test_frbsurveys.py ........                                              [100%]

=============================== warnings summary ===============================
../../../../anaconda3/lib/python3.7/site-packages/secretstorage/dhcrypto.py:16
  /home/sunil/anaconda3/lib/python3.7/site-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
    from cryptography.utils import int_from_bytes

../../../../anaconda3/lib/python3.7/site-packages/secretstorage/util.py:25
  /home/sunil/anaconda3/lib/python3.7/site-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
    from cryptography.utils import int_from_bytes

../../../../anaconda3/lib/python3.7/site-packages/pandas/util/testing.py:27
  /home/sunil/anaconda3/lib/python3.7/site-packages/pandas/util/testing.py:27: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    import pandas._libs.testing as _testing

../../../../anaconda3/lib/python3.7/site-packages/pyvo/dal/params.py:6
  /home/sunil/anaconda3/lib/python3.7/site-packages/pyvo/dal/params.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    from collections import MutableSet

../../../../anaconda3/lib/python3.7/site-packages/html5lib/_trie/_base.py:3
  /home/sunil/anaconda3/lib/python3.7/site-packages/html5lib/_trie/_base.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    from collections import Mapping

frb/tests/test_frbsurveys.py::test_sdss
  /home/sunil/anaconda3/lib/python3.7/site-packages/astroquery/sdss/core.py:865: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
    comments='#'))

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 8 passed, 6 warnings in 14.84s ========================
````

**Review by profxj — APPROVED** [review]
thx!

**Pull request merged**
